name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  IMAGE_NAME: "kube-plex"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: make build
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Log in to DO Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Tag on registry
      run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.REGISTRY }}
    - name: Push image to DO Container Registry
      run: docker push ${{ secrets.REGISTRY }}



